name: Deploy

on:
  push:
    branches:
      - main  # ose branch që dëshiron të monitorosh për deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}         # IP ose hostname i serverit
        username: ${{ secrets.SERVER_USER }}     # Përdoruesi SSH në server
        key: ${{ secrets.SERVER_SSH_KEY }}       # Çelësi privat SSH (pa passphrase)
        # passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }} # Nëse çelësi ka passphrase
        port: 22                                # Default port SSH, ndrysho nëse ke port tjetër
        script: |
          echo "Starting deploy..."
          # Komandat që do ekzekutohen në server për deploy
          cd /path/to/your/app || exit 1
          git pull origin main
          # Komanda të tjera, p.sh. ndërtim, restart shërbimi, etj.
          echo "Deploy completed!"
