version: "3.8"

services:
  app:
    image: php:7.4-cli
    container_name: php-slim-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/html/vendor
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 -t public
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always
